# Site settings
title: Wildlife in Pukaskwa National Park
description: A website showcasing wildlife in Pukaskwa National Park.

# Base URL for the site
url: "https://bobbivalentine.github.io/Wildlife-in-Pukaskwa-National-Park/"

# Theme for the site
theme: jekyll-theme-cayman