# General settings
title: "Wildlife in Pukaskwa National Park"
subtitle: "Learn About Wildlife Behavior Through Camera Traps"  # Add subtitle here
baseurl: "/Wildlife-in-Pukaskwa-National-Park"
url: "https://bobbivalentine.github.io"  # Fixed URL

# GitHub Pages settings
theme: jekyll-theme-cayman

# Build settings
source: docs        # Source folder is the 'docs' directory
destination: docs/_site  # Output folder is docs/_site

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-titles-from-headings
